name: GSI-Workshop2

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  ROM: ProjectSakura
  ROM_LINK: https://sourceforge.net/projects/projectsakura/files/phoenix/ProjectSakura-5.2-GAPPS-Core-20210810-1204-phoenix-OFFICIAL.zip/download?use_mirror=nav&r=&use_mirror=autoselect
  MIR: wet
  TZ: America/Sao_Paulo
  READ: Warning! This is A64 (Binder) based firmware.
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: Set up python
         uses: actions/setup-python@v2
         with:
           python-version: '3.8.2'

       - name: Initializing telegram bot
         env:
              TOKEN: ${{ secrets.TOKEN }}

         run: |
              sudo install telegram /usr/bin
              chmod +x $ROM/initial.sh
              . $ROM/initial.sh
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/amyGSI/ErfanGSIs
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Execute Shell Script
         env:
              TOKEN: ${{ secrets.TOKEN }}
              
         run: |
               chmod +x $ROM/build.sh
               . $ROM/build.sh
               
       - name: Copy and rename A-Only build info
         run: cp ErfanGSIs/output/*Aonly*.txt Aonly.txt

       - name: Send build info to Telegram
         env:
              CHAT_ID: ${{ secrets.CHAT_ID }}
              TOKEN: ${{ secrets.TOKEN }}
              API_ID: ${{ secrets.API_ID }}
              API_HASH: ${{ secrets.API_HASH }}

         run: |
              python telebot/robot.py
